import type { MarketplaceCategory, MarketplaceData, MarketplacePlugin } from "@harness-kit/marketplace-data";

// Generated by @harness-kit/marketplace-data at build time from this repo's
// .claude-plugin/marketplace.json + plugins/ — gitignored, same pattern as
// website/lib/marketplace/data.ts. Run `pnpm run generate:marketplace:desktop`
// (or `dev:desktop`/`build:desktop`/`install:desktop`, which do it for you)
// before working on this page; CI generates it in validate.yml/release.yml.
import generated from "./marketplace.generated.json";

const data = generated as MarketplaceData;

export function getAllPlugins(): MarketplacePlugin[] {
  return data.plugins;
}

export function getPlugin(slug: string): MarketplacePlugin | undefined {
  return data.plugins.find((p) => p.slug === slug);
}

export function getCategories(): MarketplaceCategory[] {
  return [...data.categories].sort((a, b) => a.displayOrder - b.displayOrder);
}

export function getCategoryName(slug: string): string {
  return data.categories.find((c) => c.slug === slug)?.name ?? slug;
}

export function getAllTags(): string[] {
  return [...new Set(data.plugins.flatMap((p) => p.tags))].sort();
}

/** GitHub URL for a plugin's directory in this repo, built from its repoPath. */
export function pluginRepoUrl(plugin: MarketplacePlugin): string {
  const path = plugin.repoPath.replace(/^\.\//, "");
  return `https://github.com/harnessprotocol/harness-kit/tree/main/${path}`;
}

/** Other plugins in the same category, for the detail view's "related" list. */
export function relatedPlugins(plugin: MarketplacePlugin, limit = 5): MarketplacePlugin[] {
  return data.plugins
    .filter((p) => p.slug !== plugin.slug && p.category === plugin.category)
    .sort((a, b) => a.name.localeCompare(b.name))
    .slice(0, limit);
}

export function getMarketplaceMeta(): Pick<MarketplaceData, "marketplaceName" | "owner" | "generatedAt" | "repoStars"> {
  return {
    marketplaceName: data.marketplaceName,
    owner: data.owner,
    generatedAt: data.generatedAt,
    repoStars: data.repoStars,
  };
}
