/**
 * Precompiles the Harness Protocol JSON Schema into a standalone ESM validator
 * module (src/schema/validate.generated.js).
 *
 * Why: Ajv's runtime `ajv.compile()` builds the validator with `new Function()`,
 * which requires a `script-src 'unsafe-eval'` CSP relaxation in the desktop app.
 * Standalone codegen emits the validator as plain source at build time, so the
 * shipped bundle contains no `eval`/`new Function` and the prod CSP can forbid it.
 *
 * The generated file is committed so `pnpm test` (vitest, no build step) and a
 * fresh checkout work without running this first. Regeneration is NOT automatic
 * on `pnpm build` — after editing harness.schema.json, run this script by hand
 * (`pnpm generate:validator`); CI's drift-guard step asserts the committed copy
 * is in sync (see .github/workflows/validate.yml) and fails the build otherwise.
 *
 * Usage:
 *   npx tsx packages/core/scripts/generate-validator.ts
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";
import { build } from "esbuild";
import harnessSchema from "../src/schema/harness.schema.json" with { type: "json" };
import harnessV2Schema from "../src/schema/harness-v2.schema.json" with { type: "json" };

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, "..");
const OUTPUT = resolve(PACKAGE_ROOT, "src/schema/validate.generated.js");
const OUTPUT_V2 = resolve(PACKAGE_ROOT, "src/schema/validate-v2.generated.js");

// Options MUST match the runtime consumer in src/schema/validate.ts:
// allErrors so every error surfaces, verbose to keep schema/parentSchema/data
// on error objects, plus source/esm codegen for standalone output.
const banner =
  "// @generated by scripts/generate-validator.ts — DO NOT EDIT.\n" +
  "// Regenerate with: npx tsx packages/core/scripts/generate-validator.ts\n" +
  "// Precompiled Ajv validator: self-contained ESM, no dynamic code generation.\n";

async function generate(schema: object, output: string): Promise<void> {
  const ajv = new Ajv2020({
    allErrors: true,
    verbose: true,
    code: { source: true, esm: true },
  });
  addFormats(ajv);
  const validate = ajv.compile(schema);
  const standalone = standaloneCode(ajv, validate);
  const bundled = await build({
    stdin: {
      contents: standalone,
      resolveDir: PACKAGE_ROOT,
      loader: "js",
    },
    bundle: true,
    format: "esm",
    platform: "neutral",
    mainFields: ["module", "main"],
    conditions: ["import", "default"],
    legalComments: "none",
    write: false,
  });
  const code = bundled.outputFiles[0].text;
  writeFileSync(output, banner + code);
  console.log(`Wrote standalone validator to ${output} (${code.length} bytes)`);
}

await generate(harnessSchema, OUTPUT);
await generate(harnessV2Schema, OUTPUT_V2);
