/**
 * Precompiles the Harness Protocol JSON Schema into a standalone ESM validator
 * module (src/schema/validate.generated.js).
 *
 * Why: Ajv's runtime `ajv.compile()` builds the validator with `new Function()`,
 * which requires a `script-src 'unsafe-eval'` CSP relaxation in the desktop app.
 * Standalone codegen emits the validator as plain source at build time, so the
 * shipped bundle contains no `eval`/`new Function` and the prod CSP can forbid it.
 *
 * The generated file is committed so `pnpm test` (vitest, no build step) and a
 * fresh checkout work without running this first; `prebuild` regenerates it and
 * CI asserts the committed copy is in sync (see .github/workflows/validate.yml).
 *
 * Usage:
 *   npx tsx packages/core/scripts/generate-validator.ts
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";
import { build } from "esbuild";
import harnessSchema from "../src/schema/harness.schema.json" with { type: "json" };

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, "..");
const OUTPUT = resolve(PACKAGE_ROOT, "src/schema/validate.generated.js");

// Options MUST match the runtime consumer in src/schema/validate.ts:
// allErrors so every error surfaces, plus source/esm codegen for standalone output.
const ajv = new Ajv2020({
  allErrors: true,
  code: { source: true, esm: true },
});
addFormats(ajv);

const validate = ajv.compile(harnessSchema);
const standalone = standaloneCode(ajv, validate);

// standaloneCode still emits bare `require()` calls for Ajv's runtime helpers
// (ucs2length) and ajv-formats. Those break an ESM/browser bundle, so we
// esbuild-bundle the standalone output into a single self-contained module with
// zero runtime imports — the whole point is that the shipped desktop bundle has
// no `eval`/`new Function` AND no dangling requires the browser can't resolve.
const bundled = await build({
  stdin: {
    contents: standalone,
    resolveDir: PACKAGE_ROOT,
    loader: "js",
  },
  bundle: true,
  format: "esm",
  platform: "neutral",
  mainFields: ["module", "main"],
  conditions: ["import", "default"],
  legalComments: "none",
  write: false,
});

const banner =
  "// @generated by scripts/generate-validator.ts — DO NOT EDIT.\n" +
  "// Regenerate with: npx tsx packages/core/scripts/generate-validator.ts\n" +
  "// Precompiled Ajv validator: self-contained ESM, no dynamic code generation.\n";

const code = bundled.outputFiles[0].text;
writeFileSync(OUTPUT, banner + code);
console.log(`Wrote standalone validator to ${OUTPUT} (${code.length} bytes)`);
