[[permission]]
identifier = "allow-get-custom-profile"
description = "Allows the get_custom_profile command."
commands.allow = ["get_custom_profile"]

[[permission]]
identifier = "deny-get-custom-profile"
description = "Denies the get_custom_profile command."
commands.deny = ["get_custom_profile"]
